### ISSUE TITLE
اصلاح ساختار لینک ساب سینگ باکس و مبدل

### ISSUE THREAD

**Issue by Graveyard9988** [yebekhe/TVC#1]
درود
بخش زیر در rule های شکلات وجود ندارد لطفا حلقه ی زیر را از **لینک ساب سینگ باکس** حذف کنید:
{
"geosite": [
"other"
],
"outbound": "direct"
},

سپاس

**Comment by Graveyard9988** [comment]
درود
کانفیگ زیر در مبدل شما به درستی تبدیل نمی شود
vless://2ed69b6e-06a8-42df-9248-1f4ace590c00@127.0.0.1:443/?type=http&encryption=none&flow=&host=127.0.0.1&path=%2Fcc6ac00b&sni=www.yahoo.com&alpn=h2%2Chttp%2F1.1&fp=chrome&security=reality&pbk=kZKTtjbc_e7Hu9XMOLt3n2d7hdGsRs53Obx5zWFMFE0&sid=85e9eb946f76f3f0#Reality

قالب صحیح ان پس از تبدیل به شکل زیر است: (کامنت بعد)

**Comment by Graveyard9988** [comment]
{
"tag": "Reality | 2",
"type": "vless",
"server": "127.0.0.1",
"server_port": 443,
"uuid": "2ed69b6e-06a8-42df-9248-1f4ace590c00",
"flow": "",
"packet_encoding": "xudp",
"multiplex": {
"enabled": false,
"protocol": "smux",
"max_streams": 32
},
"transport": {
"host": [
"127.0.0.1"
],
"path": "/cc6ac00b",
"type": "http"
},
"tls": {
"enabled": true,
"server_name": "www.yahoo.com",
"insecure": false,
"utls": {
"enabled": true,
"fingerprint": "chrome"
},
"reality": {
"enabled": true,
"public_key": "kZKTtjbc_e7Hu9XMOLt3n2d7hdGsRs53Obx5zWFMFE0",
"short_id": "85e9eb946f76f3f0"
}
}
},

**Comment by Graveyard9988** [comment]
همچنین کانفیگ زیر 
vless://b7d476c5-fe37-91bd-ab8c-861e7dn2c266@google.com:443?security=&alpn=http/1.1&type=tcp&path=/&headerType=http&host=speedtest1.shatel.ir,intraspeedtest2.mobinnet.ir&encryption=none#Network

پس از ایمپورت قالب صحیح ان بدین صورت باید باشد: (کامنت بعد)

**Comment by Graveyard9988** [comment]
{
      "server": google.com",
      "server_port": 443,
      "transport": {
        "host": [
          "intraspeedtest2.mobinnet.ir",
          "speedtest1.shatel.ir"
        ],
        "method": "GET",
        "path": "/",
        "type": "http"
      },
      "uuid": "b7d476c5-fe37-91bd-ab8c-861e7dn2c266",
      "type": "vless",
      "tag": "Network"
    },

**Comment by yebekhe** [comment]
> { "tag": "Reality | 2", "type": "vless", "server": "127.0.0.1", "server_port": 443, "uuid": "2fd69hge-06b8-42df-9348-1f4bce590c00", "flow": "", "packet_encoding": "xudp", "multiplex": { "enabled": false, "protocol": "smux", "max_streams": 32 }, "transport": { "host": [ "127.0.0.1" ], "path": "/cc6ac00b", "type": "http" }, "tls": { "enabled": true, "server_name": "www.yahoo.com", "insecure": false, "utls": { "enabled": true, "fingerprint": "chrome" }, "reality": { "enabled": true, "public_key": "kZKTtjbc_e7Hu9XMOLt3n2d7hdGsRs53Obx5zWFMFE0", "short_id": "85e9eb946f76f3f0" } } },

این مورد از ابتدا در این پروژه رفع شده ابتدا چک کنید!

**Comment by Graveyard9988** [comment]
در بخش مبدل یک سری نواقص داشت که احساس کردم جنریت نمی کنه واسه همین کامل و کلی فرستادم
حق با شماست.
